### ISSUE TITLE
$.browser.msie is deprecated in jquery.1.9

### ISSUE THREAD

**Issue by PDXIII** [FrediBach/jQuery-jKit#1]
Had some issues, because i referred to script src="http://code.jquery.com/jquery-latest.min.js"></script

Got this error:

Uncaught TypeError: Cannot read property 'msie' of undefined jquery.jkit.1.1.10.min.js:10
$.jKit jquery.jkit.1.1.10.min.js:10
(anonymous function) jquery.jkit.1.1.10.min.js:11
st.extend.each jquery-latest.min.js:1
st.fn.st.each jquery-latest.min.js:1
$.fn.jKit jquery.jkit.1.1.10.min.js:11
(anonymous function)

Until you'll get it fixed I'll refer to my hosted version of jquery.1.8.2

Keep On - U r doing a good job!

**Comment by FrediBach** [comment]
I will add a compatible version soon. It's relatively easy to fix in jKit, only one line that changes, but not all the sample plugins are compatibel, so I have to update the samples and demos, as well.

**Comment by PDXIII** [comment]
Great! BTW twitter bootstrap has similar problems ;-)

**Comment by FrediBach** [comment]
Fixed in version 1.1.20

**Comment by PDXIII** [comment]
Awesome!
Donna try it later.
